[variables]
NODE_ENV = "production"
NPM_CONFIG_CACHE = "/tmp/.npm"
DISABLE_ESLINT_PLUGIN = "true"

[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["npm install --prefer-offline --no-audit --no-fund"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npx serve -s build -p $PORT"
